add check docker image front&back

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -17,10 +17,10 @@ jobs:
         uses: actions/checkout@v3    
 
       # Step 2: Check if Docker Image Exists
-      - name: Check if Docker Image Exists
-        id: check_image
+      - name: Check if Docker Image pet_adopt_frontend Exists
+        id: check_image_frontend
         run: |
-          REPOSITORY="finalsprinttodoapp/myapp"  
+          REPOSITORY="${{ secrets.DOCKER_USERNAME }}/pet_adopt_frontend"  
           TAG="latest"
           
           RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_TOKEN }}" \
@@ -31,7 +31,23 @@ jobs:
               exit 1
           fi
           
-          echo "Docker image exists. Proceeding to deployment."
+          echo "Docker image pet_adopt_frontend exists. Proceeding to deployment."
+
+      - name: Check if Docker Image pet_adopt_backend Exists
+        id: check_image_backend
+        run: |
+          REPOSITORY="${{ secrets.DOCKER_USERNAME }}/pet_adopt_backend"  
+          TAG="latest"
+          
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_TOKEN }}" \
+            "https://hub.docker.com/v2/repositories/${REPOSITORY}/tags/${TAG}/")
+          
+          if [ "$RESPONSE" -ne 200 ]; then
+              echo "Docker image not found: ${REPOSITORY}:${TAG}. Exiting workflow."
+              exit 1
+          fi
+          
+          echo "Docker image pet_adopt_backend exists. Proceeding to deployment."
 
       # Step 3: Create EC2 Instance and Deploy the Application
       - name: Create EC2 Instance and Deploy the Application
